services:
# nginx ------------------------------------------------------------
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html/
    restart: unless-stopped
    networks:
      inception:

# wordpress ------------------------------------------------------------
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
      - wp_normal_password
    restart: unless-stopped
    networks:
      inception:

# mariadb ------------------------------------------------------------
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    restart: unless-stopped
    networks:
      inception:

# adminer ------------------------------------------------------------
  adminer:
    build: ./requirements/bonus/adminer/.
    container_name: adminer
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    networks:
      inception:

# redis ------------------------------------------------------------
  redis:
    build: ./requirements/bonus/redis/.
    container_name: redis
    restart: unless-stopped
    networks:
      inception:

# prometheus ------------------------------------------------------------
  prometheus:
    build: ./requirements/bonus/prometheus/.
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      inception:

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  wp_normal_password:
    file: ../secrets/wp_normal_password.txt

networks:
  inception:
    name: inception-network
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/samatsum/data/mariadb
      o: bind

  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/samatsum/data/wordpress
      o: bind

  prometheus_data:
    name: prometheus
    driver: local
    driver_opts:
      type: none
      device: /home/samatsum/data/prometheus
      o: bind
