#このファイルは、PHP-FPM（FastCGI Process Manager）という
#「PHPを実行するための専用ワーカ-」たちの働き方を定義する設定ファイル

[www]

# 実行権限の制御
# もしWordPressのPHPコードに脆弱性があり、攻撃者に悪意のあるコードを実行されたとしても、
# その被害は www-data がアクセスできる範囲（/var/www/html など）に限定されます。
user = www-data
group = www-data

# OSのネットワークスタックに対し、「TCPポートの9000番を開けて、
# 外部からの接続を待て（bind() および listen() システムコール）」と命令
# NGINXコンテナの fastcgi_pass wordpress:9000; という設定と完全にペア
# NGINXが受付で受け取ったPHPの処理依頼を、この9000番ポートに投げ込んできます
listen = wp-php:9000

# listen.owner = www-data
# listen.group = www-data

# プロセスの「動的」な生成、削除(memori ryouni yoru)
pm = dynamic

pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

# Prometheusが定期的にこの /status をスクレイピング（情報収集）しに行き、
# そのデータを元にGrafanaで「PHP-FPM Active Processes」というグラフを描画する仕組み
pm.status_path = /status
