global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus自身を監視する
  - job_name: 'prometheus'
    # メトリクスの取得先を新しい空間（/prometheus/metrics）に変更する
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']
